language: python
branches:
  only:
  - first-theme
install:
- pip install pelican ghp-import
addons:
  apt:
    packages:
    - asciidoc
script:
- make publish github
env:
  global:
  - GH_USER=chopskxw
  - GH_REPO=chopskxw.github.io
  - GH_BRANCH=master
  - secure: C1bfBsM4VpJ7LsWPL81qBc/zk2u0eKpboxyt3p6D683BCSNQDy1jGJzLyr6ZD+83+08Tohh+4WcMdNy0ZqRuK54fov6t1hCfnKju1vBjhP3BNxQ8CgdR4iF5lwsIIGO8cewxG3gq8Q7/UtVKW0AXeUpISUDTZjd2gIG3Xzi5KR6zYSm6Yb0xrqFY+Dejr7GTVYpNh3P5+uhIg4+xuKdDMHDLNNGFV9vBgQkPX/roEA48LjGDdxEccHmukx8H0Ji6T5wkPOEvTp9pPNN0a9JJ1g7PDhN4pftKAG6l9Gq0HtNMRem4bGDFxY+qJdkqO8E7ZdXb5Mjq7A7VlmUCMPwWZ9EG3E4MsxvENsfnuzwVBfpX5sONAA3IKByviZPGMb/h0es49YHKuxFEqj9X5rF0OM24QJRD1rXmEneGjZEMS47dl0LjtOwrFzJSlwooJKCT8FHMFAoKE6V26DkdKDVfxzyhaCIbWwBTPPijhe6g1xMg7AXSZxkpHohf+Ou7RD0kckB3NAr21urE/zfuN+G9fsnyLd+sai1EnZC2mt4u8OlT+xiUNicLp52ojl21hoNxAIo/hdtZjMsc3pKeivXm445KFsGsAetceXaYd2ZMUZjztvhvOtuAPym+5bOZVxCE7HCQPSzfrfMA8vT9lSptkSQnMAjxmYza+nCw6JKNVgw=
